# Default config
# Helpful messages are printed if there are any errors

crewMember:
  id: 1 # Int
  # String
  # For String only, comments on the same line are not supported,
  # and are counted as the string
  name: James
  job: 1 # Int
  currentRoom: 1 # Int

room:
  id: 1 # Int
  # String
  name: Medbay 1
  type: 2 # Int
  size: 25 # Int
  maxCrew: 8 # Int
  storage: 8 # Int
  # The Ids of the adjacent rooms. They are separated by a coma and as little
  # or as many space as you want. Start with '[' and ends with ']'
  adjacentRooms: [3,  2  ] # Int[]


room:
  id: 2 # Int
  # String
  name: Medbay 1
  type: 2 # Int
  size: 25 # Int
  maxCrew: 8 # Int
  storage: 8 # Int
  adjacentRooms: [] # Int[]

room:
  id: 3 # Int
  # String
  name: Medbay 1
  type: 2 # Int
  size: 25 # Int
  maxCrew: 8 # Int
  storage: 8 # Int
  adjacentRooms: [] # Int[]