# Default config
# Helpful messages are printed if there are any errors

crewMember:
  id: 1 # Int
  # String
  # For String only, comments on the same line are not supported,
  # and are counted as the string
  name: James
  job: 1 # Int
  currentRoom: 1 # Int

room:
  id: 1 # Int
  # String
  name: Corridor Medbay to Bridge
  type: 1 # Int
  size: 25 # Int
  maxCrew: 8 # Int
  storage: 8 # Int
  # The Ids of the adjacent rooms. They are separated by a coma and as little
  # or as many space as you want. Start with '[' and ends with ']'

  # Note that you can omit to repeat yourself : i.e if Room #1 has #2 as adjacent,
  # you don't have to specify that #1 as adjacent to Room #2
  adjacentRooms: [3  ] # Int[]


room:
  id: 2 # Int
  # String
  name: Medbay 1
  type: 2 # Int
  size: 35 # Int
  maxCrew: 20 # Int
  storage: 30 # Int
  adjacentRooms: [] # Int[]

room:
  id: 3 # Int
  # String
  name: Main bridge
  type: 4 # Int
  size: 20 # Int
  maxCrew: 5 # Int
  storage: 5 # Int
  adjacentRooms: [2] # Int[]